name: On Pull Request

on:
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: fedora-rust-builder

jobs:
  docker-build-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Try Build
      run: |
        # Build Image
        docker build -f Dockerfile -t $IMAGE_NAME .
