name: Docker Image CI

on:
  release:
    types: [published]

env:
  IMAGE_NAME: fedora-rust-builder

jobs:
  docker-publish-stable:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build & Publish
      run: |
        # Build Image
        docker build -f Dockerfile -t $IMAGE_NAME .

        # Login Github Docker Registry
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        # Github Package Registry Tag & Push
        IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME 
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        VERSION=latest
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
